{% set name = "rocksdb" %}
{% set version = "6.27.3" %}

package:
  name: rocksdb
  version: {{ version }}

source:
  folder: src
  url: https://github.com/facebook/rocksdb/archive/v{{ version }}.tar.gz
  sha256: ee29901749b9132692b26f0a6c1d693f47d1a9ed8e3771e60556afe80282bf58

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # Symbols are removed from a minor release to the next.
    # https://abi-laboratory.pro/index.php?view=timeline&l=rocksdb
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.5.1,<4
    - ninja >=1.10,<2
  host:
    - gflags
    - jemalloc
    - lz4-c
    - snappy
    - zstd

test:
  commands:
    - test -f ${PREFIX}/lib/librocksdb.a
    - test -f ${PREFIX}/lib/librocksdb.dylib  # [osx]
    - test -f ${PREFIX}/lib/librocksdb.so     # [linux]
    - test -f ${PREFIX}/include/rocksdb/db.h

about:
  home: https://rocksdb.org
  license: Apache-2.0
  license_file: src/LICENSE.Apache
  summary: A library that provides an embeddable, persistent key-value store for fast storage.

  dev_url: https://github.com/facebook/rocksdb
  doc_url: https://rocksdb.org/docs

extra:
  recipe-maintainers:
    - benhuff
    - oblute
    - rluria14
    - sodre
