{% set name = "rocksdb" %}
{% set version = "9.4.0" %}

package:
  name: rocksdb
  version: {{ version }}

source:
  folder: src
  url: https://github.com/facebook/rocksdb/archive/v{{ version }}.tar.gz
  sha256: 1f829976aa24b8ba432e156f52c9e0f0bd89c46dc0cc5a9a628ea70571c1551c

build:
  number: 0
  run_exports:
    # Symbols are removed from a minor release to the next.
    # https://abi-laboratory.pro/index.php?view=timeline&l=rocksdb
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.5.1,<4
    - ninja >=1.10,<2
  host:
    - gflags
    - jemalloc  # [not win]
    - lz4-c
    - snappy
    - zstd
    - bzip2
    - zlib

test:
  commands:
    - test -f ${PREFIX}/lib/librocksdb.a                           # [unix]
    - test -f ${PREFIX}/lib/librocksdb${SHLIB_EXT}                 # [unix]
    - test -f ${PREFIX}/include/rocksdb/db.h                       # [unix]
    - if not exist %LIBRARY_PREFIX%\lib\rocksdb.lib exit 1         # [win]
    - if not exist %LIBRARY_PREFIX%\lib\rocksdb-shared.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\include\rocksdb\db.h exit 1    # [win]

about:
  home: https://rocksdb.org
  license: Apache-2.0
  license_file: src/LICENSE.Apache
  summary: A library that provides an embeddable, persistent key-value store for fast storage.

  dev_url: https://github.com/facebook/rocksdb
  doc_url: https://rocksdb.org/docs

extra:
  recipe-maintainers:
    - jjerphan
    - benhuff
    - oblute
    - rluria14
    - sodre
